import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  X, User, Building2, Ship, HelpCircle, Calendar, Globe,
  MapPin, FileText, Hash, AlertTriangle, Copy, ExternalLink, Download
} from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface RecordModalProps {
  recordId: number;
  onClose: () => void;
}

export default function RecordModal({ recordId, onClose }: RecordModalProps) {
  const { data: record, isLoading } = trpc.search.getRecord.useQuery({ id: recordId });

  const [isDownloading, setIsDownloading] = useState(false);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard`);
  };

  const downloadReport = async () => {
    if (!record) return;
    setIsDownloading(true);
    try {
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 15;
      const contentW = pageW - margin * 2;
      let y = 0;

      // ── HEADER BACKGROUND ──
      doc.setFillColor(26, 26, 46);
      doc.rect(0, 0, pageW, 28, "F");

      // Gold bar
      doc.setFillColor(193, 127, 62);
      doc.rect(0, 28, pageW, 2, "F");

      // Header text (LTR English)
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(255, 255, 255);
      doc.text("SanctionCheck", margin, 12);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(148, 163, 184);
      doc.text("Sanctions Screening Platform", margin, 18);

      // Header right side
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(255, 255, 255);
      doc.text("Sanctions Screening Report", pageW - margin, 12, { align: "right" });
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(193, 127, 62);
      doc.text("Al-Mustashar Legal Consultancy", pageW - margin, 18, { align: "right" });

      y = 38;

      // ── ALERT BANNER ──
      doc.setFillColor(254, 242, 242);
      doc.setDrawColor(220, 38, 38);
      doc.setLineWidth(0.5);
      doc.roundedRect(margin, y, contentW, 14, 2, 2, "FD");
      // Red left bar
      doc.setFillColor(220, 38, 38);
      doc.rect(margin, y, 3, 14, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(220, 38, 38);
      doc.text("SANCTIONED ENTITY", pageW / 2, y + 6, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(153, 27, 27);
      doc.text("This entity appears on international sanctions lists", pageW / 2, y + 11, { align: "center" });
      y += 20;

      // ── META BAR ──
      doc.setFillColor(255, 251, 235);
      doc.setDrawColor(253, 230, 138);
      doc.roundedRect(margin, y, contentW, 14, 2, 2, "FD");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(108, 117, 125);
      const reportDate = new Date().toLocaleString("en-GB");
      doc.text(`Screening Date: ${reportDate}`, margin + 4, y + 5);
      doc.text(`Record ID: ${record.referenceNumber || `ID-${record.id}`}`, margin + 4, y + 10);
      doc.text("Generated by SanctionCheck", pageW - margin - 4, y + 5, { align: "right" });
      y += 20;

      // ── HELPER: Section Header ──
      const sectionHeader = (title: string) => {
        doc.setFillColor(241, 245, 249);
        doc.rect(margin, y, contentW, 8, "F");
        doc.setFillColor(193, 127, 62);
        doc.rect(margin, y, 2.5, 8, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(26, 26, 46);
        doc.text(title, margin + 6, y + 5.5);
        y += 12;
      };

      // ── HELPER: Field ──
      const field = (label: string, value: string | null | undefined, x: number, w: number) => {
        if (!value) return;
        doc.setFillColor(248, 249, 250);
        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.3);
        doc.roundedRect(x, y, w, 14, 1.5, 1.5, "FD");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(108, 117, 125);
        doc.text(label, x + 3, y + 5);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(26, 26, 46);
        const truncated = value.length > 45 ? value.substring(0, 42) + "..." : value;
        doc.text(truncated, x + 3, y + 11);
      };

      const checkNewPage = (needed: number) => {
        if (y + needed > pageH - 20) {
          doc.addPage();
          y = 15;
        }
      };

      // ── PRIMARY NAMES ──
      sectionHeader("Primary Names / الأسماء الأساسية");
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.roundedRect(margin, y, contentW, record.nameAr ? 22 : 14, 2, 2, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(26, 26, 46);
      doc.text(record.nameEn || "—", margin + 4, y + 9);
      if (record.nameAr) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(108, 117, 125);
        doc.text(record.nameAr, margin + 4, y + 18);
      }
      y += record.nameAr ? 28 : 20;

      // Alt names
      const altNames = (record.alternativeNames as string[] | null) || [];
      if (altNames.length > 0) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7.5);
        doc.setTextColor(148, 163, 184);
        const altText = "AKA: " + altNames.slice(0, 5).join(" | ");
        doc.text(altText, margin, y);
        y += 6;
      }
      y += 4;

      // ── ENTITY DETAILS ──
      checkNewPage(30);
      sectionHeader("Entity Details / تفاصيل الكيان");
      const halfW = (contentW - 4) / 2;
      field("Entity Type / نوع الكيان", record.entityType, margin, halfW);
      field("Nationality / الجنسية", record.nationality, margin + halfW + 4, halfW);
      y += 18;
      if (record.dateOfBirth || record.placeOfBirth) {
        field("Date of Birth / تاريخ الميلاد", record.dateOfBirth, margin, halfW);
        field("Place of Birth / مكان الميلاد", record.placeOfBirth, margin + halfW + 4, halfW);
        y += 18;
      }
      y += 4;

      // ── LISTING INFORMATION ──
      checkNewPage(50);
      sectionHeader("Listing Information / معلومات الإدراج");
      field("Issuing Body / الجهة المدرجة", record.issuingBody, margin, halfW);
      field("Listing Date / تاريخ الإدراج", record.listingDate, margin + halfW + 4, halfW);
      y += 18;
      if (record.legalBasis) {
        field("Legal Basis / السند القانوني", record.legalBasis, margin, contentW);
        y += 18;
      }
      if (record.listingReason) {
        checkNewPage(20);
        field("Listing Reason / سبب الإدراج", record.listingReason, margin, contentW);
        y += 18;
      }
      if (record.actionTaken) {
        checkNewPage(20);
        field("Action Taken / الإجراء المتخذ", record.actionTaken, margin, contentW);
        y += 18;
      }
      y += 4;

      // ── NOTES ──
      if (record.notes) {
        checkNewPage(30);
        sectionHeader("Notes / ملاحظات");
        doc.setFillColor(255, 251, 235);
        doc.setDrawColor(253, 230, 138);
        doc.setLineWidth(0.3);
        const noteLines = doc.splitTextToSize(record.notes, contentW - 8);
        const noteH = noteLines.length * 5 + 8;
        checkNewPage(noteH + 4);
        doc.roundedRect(margin, y, contentW, noteH, 2, 2, "FD");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(26, 26, 46);
        doc.text(noteLines, margin + 4, y + 6);
        y += noteH + 8;
      }

      // ── FOOTER ──
      const footerY = pageH - 14;
      doc.setDrawColor(193, 127, 62);
      doc.setLineWidth(0.8);
      doc.line(margin, footerY - 2, pageW - margin, footerY - 2);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(108, 117, 125);
      doc.text("This report is for compliance and due diligence purposes only. Always verify with official sanctions lists.", pageW / 2, footerY + 2, { align: "center" });
      doc.setTextColor(193, 127, 62);
      doc.setFont("helvetica", "bold");
      doc.text(`SanctionCheck © ${new Date().getFullYear()} — Al-Mustashar Legal Consultancy`, pageW / 2, footerY + 7, { align: "center" });

      // ── SAVE ──
      const filename = `sanctions-report-${record.referenceNumber || recordId}-${Date.now()}.pdf`;
      doc.save(filename);
      toast.success("تم تحميل التقرير بنجاح");
    } catch (err) {
      console.error("PDF error:", err);
      toast.error("حدث خطأ أثناء إنشاء التقرير");
    } finally {
      setIsDownloading(false);
    }
  };

  const entityIcon =
    record?.entityType === "individual" ? <User size={16} /> :
    record?.entityType === "organisation" ? <Building2 size={16} /> :
    record?.entityType === "vessel" ? <Ship size={16} /> :
    <HelpCircle size={16} />;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-destructive/20 flex items-center justify-center text-destructive">
              {entityIcon}
            </div>
            <div>
              <div className="text-xs text-muted-foreground uppercase tracking-wider">Record Detail</div>
              <div className="text-sm font-semibold text-foreground">
                {record?.referenceNumber || `ID: ${recordId}`}
              </div>
            </div>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8">
            <X size={16} />
          </Button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {isLoading ? (
            <div className="flex items-center justify-center py-12">
              <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
            </div>
          ) : record ? (
            <>
              {/* Alert Banner */}
              <div className="flex items-center gap-3 p-3 rounded-lg bg-destructive/10 border border-destructive/30">
                <AlertTriangle size={16} className="text-destructive flex-shrink-0" />
                <div>
                  <div className="text-sm font-semibold text-destructive">SANCTIONED ENTITY</div>
                  {record.actionTaken && (
                    <div className="text-xs text-destructive/80 mt-0.5">{record.actionTaken}</div>
                  )}
                </div>
              </div>

              {/* Primary Names */}
              <div className="space-y-3">
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Primary Names</h3>
                <div className="bg-muted/50 rounded-lg p-4 space-y-2 border border-border">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <div className="text-xs text-muted-foreground mb-0.5">English</div>
                      <div className="text-base font-semibold text-foreground">{record.nameEn}</div>
                    </div>
                    <button
                      onClick={() => copyToClipboard(record.nameEn, "Name")}
                      className="text-muted-foreground hover:text-foreground mt-1"
                    >
                      <Copy size={13} />
                    </button>
                  </div>
                  {record.nameAr && (
                    <div className="flex items-start justify-between gap-2 pt-2 border-t border-border">
                      <div>
                        <div className="text-xs text-muted-foreground mb-0.5">Arabic</div>
                        <div className="text-base font-semibold text-foreground" dir="rtl">{record.nameAr}</div>
                      </div>
                      <button
                        onClick={() => copyToClipboard(record.nameAr!, "Arabic name")}
                        className="text-muted-foreground hover:text-foreground mt-1"
                      >
                        <Copy size={13} />
                      </button>
                    </div>
                  )}
                </div>
              </div>

              {/* Alternative Names */}
              {record.alternativeNames && (record.alternativeNames as string[]).length > 0 && (
                <div className="space-y-2">
                  <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                    Alternative Names / AKA
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {(record.alternativeNames as string[]).map((name, i) => (
                      <Badge key={i} variant="secondary" className="text-xs font-normal">
                        {name}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}

              <Separator className="bg-border" />

              {/* Personal Details */}
              <div className="space-y-3">
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Details</h3>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { label: "Entity Type", value: record.entityType, icon: entityIcon },
                    { label: "Nationality", value: record.nationality, icon: <Globe size={13} /> },
                    { label: "Date of Birth", value: record.dateOfBirth, icon: <Calendar size={13} /> },
                    { label: "Place of Birth", value: record.placeOfBirth, icon: <MapPin size={13} /> },
                  ].map((item) => item.value && (
                    <div key={item.label} className="bg-muted/40 rounded-lg p-3 border border-border/50">
                      <div className="flex items-center gap-1.5 text-xs text-muted-foreground mb-1">
                        {item.icon}
                        {item.label}
                      </div>
                      <div className="text-sm text-foreground font-medium capitalize">{item.value}</div>
                    </div>
                  ))}
                </div>
              </div>

              <Separator className="bg-border" />

              {/* Listing Details */}
              <div className="space-y-3">
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Listing Information</h3>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { label: "Issuing Body", value: record.issuingBody },
                    { label: "Listing Reason", value: record.listingReason },
                    { label: "Listing Date", value: record.listingDate },
                    { label: "Legal Basis", value: record.legalBasis },
                    { label: "Reference Number", value: record.referenceNumber },
                  ].map((item) => item.value && (
                    <div key={item.label} className="bg-muted/40 rounded-lg p-3 border border-border/50">
                      <div className="text-xs text-muted-foreground mb-1">{item.label}</div>
                      <div className="text-sm text-foreground font-medium">{item.value}</div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Notes */}
              {record.notes && (
                <div className="space-y-2">
                  <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
                    <FileText size={12} />
                    Notes
                  </h3>
                  <div className="bg-muted/40 rounded-lg p-3 text-sm text-muted-foreground leading-relaxed border border-border/50">
                    {record.notes}
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="text-center py-12 text-muted-foreground">Record not found</div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-4 border-t border-border">
          <div className="text-xs text-muted-foreground">
            Record ID: {recordId}
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={onClose} className="border-border">
              Close
            </Button>
            {record && (
              <>
                <Button
                  variant="outline"
                  size="sm"
                  className="border-border"
                  onClick={() => copyToClipboard(JSON.stringify(record, null, 2), "Record data")}
                >
                  <Copy size={13} className="mr-1.5" />
                  Copy Data
                </Button>
                <Button
                  size="sm"
                  disabled={isDownloading}
                  onClick={downloadReport}
                  className="text-white font-semibold"
                  style={{ background: isDownloading ? "#999" : "linear-gradient(135deg, #C17F3E, #a06830)" }}
                >
                  {isDownloading ? (
                    <>
                      <div className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin mr-1.5" />
                      جاري التحميل...
                    </>
                  ) : (
                    <>
                      <Download size={13} className="mr-1.5" />
                      تنزيل التقرير
                    </>
                  )}
                </Button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
